version: 2

sphinx:
  configuration: doc/source/conf.py

python:
  install:
  - method: setuptools
    path: .
  - requirements: doc/requirements.txt

formats:
   - htmlzip

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - build-essential
    - gir1.2-gtk-3.0
    - gir1.2-rsvg-2.0
    - gobject-introspection
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtksourceview-3.0-dev
    - libjpeg-dev
    - libpango1.0-dev
    - python3-dev
    - python3-gi
    - python3-gi-cairo
    - python3-wrapt
