.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SHOEBOT-IDE 1 "February 20, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
shoebot\-ide \- A simple graphical IDE for Shoebot scripts
.SH SYNOPSIS
.B shoebot\-ide
.RI [ inputfile.bot ]
.SH DESCRIPTION
.PP
This manual page documents briefly the
\fBshoebot-ide\fR
command\.
.PP
Shoebot is a pure Python graphics robot: It takes a Python script as
input, which describes a drawing process, and outputs a graphic in a
common open standard format (SVG, PDF, PostScript, or PNG)\. It has a
simple text editor GUI, and scripts can describe their own GUIs for
controlling variables interactively\. Being pure Python, it can also
be used as a Python module, a plugin for Python\-scriptable tools such
as Inkscape, and run from the command line\. This man page focuses on
the \fBshoebot-ide\fR graphical IDE\.
.SH "SEE ALSO"
.PP
sbot (1)\.
.PP
The programs are documented fully at the Shoebot website available at http://tinkerhouse\.net/shoebot\.
.SH "AUTHOR"
.PP
This manual page was written by Ricardo Lafuente
<r@sollec\.org>
for the
Debian(TM)
system (but may be used by others)\. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 3 any later version published by the Free Software Foundation\.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\.
.SH "COPYRIGHT"
Copyright \(co 2008 Ricardo Lafuente
.br
